name: Feature request
description: Suggest an idea for esign-repo
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Proposed solution
      placeholder: How should it work?
    validations:
      required: true
